DATA-737 h3 start-agent; long-lived agent process for automatically launching NodeZero

diff --git a/bin/h3 b/bin/h3
--- a/bin/h3
+++ b/bin/h3
@@ -29,28 +29,33 @@ h3-cli: A command-line utility for the Horizon3 API.
 
 Usage:
 
-h3 hello-world                  # Tests basic connectivity with the Horizon3 API.
-h3 whoami                       # Returns information about the user account attached to the API key.
-h3 pentests [{search}]          # The list of pentests in the account, optionally filtered by {search}.
-h3 pentest [{op_id}]            # The pentest for the given {op_id}, or latest-pentest by default.
-h3 latest-pentest               # Returns the most recently scheduled pentest in the account.
-h3 schedule-pentest [{options}] # Schedule a pentest using the given optional {options}
-h3 launch-nodezero [{op_id}]    # Download and run NodeZero for the given {op_id, or latest-pentest by default.
-h3 run-pentest [{options}]      # Combines schedule-pentest and launch-nodezero.
-h3 run-pentests {input-file}    # Reads {options} line-by-line from the given {input-file} and runs each pentest sequentially.
-h3 pause-pentest [{op_id}]      # Pauses the given {op_id}, or latest-pentest by default.
-h3 resume-pentest [{op_id}]     # Resumes the given {op_id}, or latest-pentest by default.
-h3 cancel-pentest [{op_id}]     # Ends the given {op_id}, or latest-pentest by default.
-h3 pentest-reports [{op_id}]    # Downloads pentest-reports-{op_id}.zip for the given {op_id}, or latest-pentest by default.
-h3 auth [force]                 # Authenticate to the API.
-h3 gql {graphql-file}           # Run the GraphQL request in the given {graphql-file}.
-h3 checkenv                     # Run the checkenv script to check for NodeZero compatibility.
-h3 accounts [{search}]          # List of client accounts this user has access to, optionally filtered by {search}.
-h3 users                        # List of users with access to the current client account.
-h3 op-templates [{op-type}]     # Pentest templates for the current client account.  op-type can be either "NodeZero" (default) or "ExternalAttack".
-h3 op-template {uuid}           # Pentest template with the given uuid.
-h3 asset-groups [{search}]      # List of asset groups in the account, optionally filtered by {search}.
-h3 asset-group {uuid}           # The asset group with the given uuid.
+h3 hello-world                      # Tests basic connectivity with the Horizon3 API.
+h3 whoami                           # Returns information about the user account attached to the API key.
+h3 pentests [{search}]              # The list of pentests in the account, optionally filtered by {search}.
+h3 pentest [{op_id}]                # The pentest for the given {op_id}, or latest-pentest by default.
+h3 latest-pentest                   # Returns the most recently scheduled pentest in the account.
+h3 schedule-pentest [{options}]     # Schedule a pentest using the given optional {options}
+h3 run-nodezero [{op_id}]           # Download and run NodeZero for the given {op_id, or latest-pentest by default.
+h3 run-pentest [{options}]          # Combines schedule-pentest and run-nodezero.
+h3 run-pentests {input-file}        # Reads {options} line-by-line from the given {input-file} and runs each pentest sequentially.
+h3 pause-pentest [{op_id}]          # Pauses the given {op_id}, or latest-pentest by default.
+h3 resume-pentest [{op_id}]         # Resumes the given {op_id}, or latest-pentest by default.
+h3 cancel-pentest [{op_id}]         # Ends the given {op_id}, or latest-pentest by default.
+h3 pentest-reports [{op_id}]        # Downloads pentest-reports-{op_id}.zip for the given {op_id}, or latest-pentest by default.
+h3 auth [force]                     # Authenticate to the API.
+h3 gql {graphql-file}               # Run the GraphQL request in the given {graphql-file}.
+h3 checkenv                         # Run the checkenv script to check for NodeZero compatibility.
+h3 accounts [{search}]              # List of client accounts this user has access to, optionally filtered by {search}.
+h3 users                            # List of users with access to the current client account.
+h3 op-templates [{op-type}]         # Pentest templates for the current client account.  op-type can be either "NodeZero" (default) or "ExternalAttack".
+h3 op-template {uuid}               # Pentest template with the given uuid.
+h3 asset-groups [{search}]          # List of asset groups in the account, optionally filtered by {search}.
+h3 asset-group {uuid}               # The asset group with the given uuid.
+h3 start-agent {name} {log-file}    # Runs the agent as a background daemon and assigns it the given {name}.  The agent logs to {log-file}.
+h3 hello-agent {name}               # Sends a hello-world command to the agent with the assigned {name}.
+h3 stop-agent                       # Stops the agent running on the local machine.
+h3 ps-agent                         # Shows the running agent process.
+h3 agents                           # List of agents in the current client account.
 
 
 Defaults to latest-pentest: 
@@ -134,7 +139,6 @@ HERE
     fi 
     return $rc
 }
-
 
 
 function cmd_client_accounts {
@@ -235,6 +239,54 @@ function cmd_env {
 }
 
 
+function ps_agent {
+    ps -ef | grep h3-start-agent | grep -v grep
+}
+
+
+function pkill_agent {
+    echoerr "Killing any running agents via: pkill -f h3-start-agent"
+    ps_agent
+    pkill -f h3-start-agent
+    sleep 2
+}
+
+
+function cmd_start_agent {
+    agent_name=$1
+    log_file=$2
+    if [ -z "$agent_name" -o -z "$log_file" ]; then
+        echo "agent_name and log_file are required"
+        return 1
+    fi
+    pkill_agent
+    echoerr "Starting agent via: nohup h3-start-agent \"$agent_name\" < /dev/null >> \"$log_file\" 2>&1 &"
+    nohup h3-start-agent "$agent_name" < /dev/null >> "$log_file" 2>&1 &
+    rc=$?
+    if [ $rc -eq 0 ]; then 
+        echoerr "Stream the agent logs via: tail -f $log_file"
+    fi
+    return $rc
+}
+
+
+function cmd_hello_agent {
+    json_params=`cat <<HERE
+{"input":{"name":"$*"}}
+HERE
+`
+    res=`h3-gql hello_agent $json_params` 
+    rc=$?
+    if [ $rc -eq 0 ]; then
+        cat <<<$res | jq .data.hello_agent
+    else
+        echo $res
+    fi 
+    return $rc
+}
+
+
+
 # -----------
 # big cmd switch 
 # -----------
@@ -284,8 +336,8 @@ elif [ "$cmd" = "run-pentests" -o "$cmd" = "run_pentests" ]; then
 elif [ "$cmd" = "cancel-pentest" -o "$cmd" = "cancel_pentest" ]; then
     h3-cancel-pentest $*
 
-elif [ "$cmd" = "launch-nodezero" -o "$cmd" = "launch_nodezero" ]; then
-    h3-launch-nodezero $*
+elif [ "$cmd" = "launch-nodezero" -o "$cmd" = "launch_nodezero" -o "$cmd" = "run-nodezero" -o "$cmd" = "run_nodezero" ]; then
+    h3-run-nodezero $*
 
 elif [ "$cmd" = "pause-pentest" -o "$cmd" = "pause_pentest" ]; then
     h3-pause-pentest $*
@@ -316,6 +368,22 @@ elif [ "$cmd" = "asset-groups" -o "$cmd" = "asset_groups" ]; then
 
 elif [ "$cmd" = "asset-group" -o "$cmd" = "asset_group" ]; then
     cmd_asset_group $*
+
+elif [ "$cmd" = "start-agent" -o "$cmd" = "start_agent" ]; then
+    cmd_start_agent $*
+
+elif [ "$cmd" = "stop-agent" -o "$cmd" = "stop_agent" ]; then
+    pkill_agent
+
+elif [ "$cmd" = "ps-agent" -o "$cmd" = "ps_agent" ]; then
+    ps_agent
+
+elif [ "$cmd" = "hello-agent" -o "$cmd" = "hello_agent" ]; then
+    cmd_hello_agent $*
+
+elif [ "$cmd" = "agents" ]; then
+    h3-gql agents | jq .data.agents[]
+
 
 else 
     echoerr "ERROR: unrecognized command: \"$cmd\".  Run \"h3 help\" for usage info."
