add cli folder to s3 locations

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -61,13 +61,13 @@ stage-deploy:
 
     # Upload easy_install script to S3
     - sha256sum easy_install.sh > easy_install.sha256.checksum
-    - aws s3 cp easy_install.sh s3://downloads-devstage-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
-    - aws s3 cp easy_install.sha256.checksum s3://downloads-devstage-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp easy_install.sh s3://downloads-devstage-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp easy_install.sha256.checksum s3://downloads-devstage-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
 
     # Upload h3-cli to S3
     - sha256sum h3-cli.zip > h3-cli.sha256.checksum
-    - aws s3 cp h3-cli.zip s3://downloads-devstage-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
-    - aws s3 cp h3-cli.sha256.checksum s3://downloads-devstage-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp h3-cli.zip s3://downloads-devstage-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp h3-cli.sha256.checksum s3://downloads-devstage-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
   rules:
     - !reference [.deploy-stage, rules]
 
@@ -99,26 +99,26 @@ production-deploy:
 
     # Upload to S3
     - sha256sum easy_install.sh > easy_install.sha256.checksum
-    - aws s3 cp easy_install.sh s3://downloads-prod-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
-    - aws s3 cp easy_install.sha256.checksum s3://downloads-prod-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp easy_install.sh s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp easy_install.sha256.checksum s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
 
     # Upload to S3
     - sha256sum h3-cli.zip > h3-cli.sha256.checksum
-    - aws s3 cp h3-cli.zip s3://downloads-prod-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
-    - aws s3 cp h3-cli.sha256.checksum s3://downloads-prod-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp h3-cli.zip s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp h3-cli.sha256.checksum s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
 
     # Upload to S3 with Tag name
     - EASY_INSTALL_NAME="easy_install-$CI_COMMIT_TAG"
     - sha256sum $EASY_INSTALL_NAME.sh > $EASY_INSTALL_NAME.sha256.checksum
-    - aws s3 cp $EASY_INSTALL_NAME.sh s3://downloads-prod-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
-    - aws s3 cp $EASY_INSTALL_NAME.sha256.checksum s3://downloads-prod-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp $EASY_INSTALL_NAME.sh s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp $EASY_INSTALL_NAME.sha256.checksum s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
 
     # Upload to S3 with Tag name
     - H3_CLI_NAME="h3-cli-$CI_COMMIT_TAG"
     - mv h3-cli.zip $H3_CLI_NAME.zip
     - sha256sum H3_CLI_NAME.zip > H3_CLI_NAME.sha256.checksum
-    - aws s3 cp H3_CLI_NAME.zip s3://downloads-prod-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
-    - aws s3 cp H3_CLI_NAME.sha256.checksum s3://downloads-prod-us-east-1/utilities/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp H3_CLI_NAME.zip s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
+    - aws s3 cp H3_CLI_NAME.sha256.checksum s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
   rules:
     - !reference [.deploy-production, rules]
 
@@ -159,7 +159,10 @@ push-to-public-branch:
     # This is to ensure that the public branch only has the latest release without a commit history.
     # - git checkout public
     - git checkout public-20250328
-    - git merge --squash $BRANCH_NAME
+    - if [[ !$(git merge --squash $BRANCH_NAME) ]]; then
+        echo "Squash merge failed";
+        exit 1;
+      fi
     - git commit -m "Release h3-cli $TIMESTAMP"
 
     # Push to public branch
